#define SPEED_READ_PIN A0
#define SPEED_ANALOGREAD_HIGH 700
#define SPEED_ANALOGREAD_LOW 580
#define SPEED_POINT_COUNT 1  //check point count
#define WHEEL_PERIMETER 2075 // mm
#define MIN_TIME 1000*5
