#define SPEED_READ_PIN A7
#define SPEED_ANALOGREAD_HIGH 700
#define SPEED_ANALOGREAD_LOW 580
#define SPEED_POINT_COUNT 1  //check point count
#define WHEEL_PERIMETER 2075 // mm
#define MIN_TIME 1000*5


#define HARDWARE_SERIAL_RATE 9600

#define SOFTDWARE_SERIAL_RATE 9600
#define SOFTDWARE_SERIAL_RX 11
#define SOFTDWARE_SERIAL_TX 10
